name: Build Backend Container

on:
  push:
    paths:
      - 'backend/**'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      tagged: ${{ steps.tag_check.outputs.tagged }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if commit is tagged
        id: tag_check
        run: |
          set -e
          git fetch --tags
          TAG=$(git tag --points-at HEAD)
          echo "::notice::Tag found: $TAG"
          if [ -z "$TAG" ]; then
            echo "tagged=false" >> $GITHUB_OUTPUT
          else
            echo "tagged=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

  build-backend:
    needs: check-tag
    if: needs.check-tag.outputs.tagged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend container
        run: |
          TAG=$(git tag --points-at HEAD)
          echo "Building and pushing backend container with tag: $TAG"
          docker build -t your-dockerhub-user/backend:$TAG ./backend
          docker push your-dockerhub-user/backend:$TAG
